theme: jekyll-theme-minimal
title: Portfólio
logo: asset/circle-euler.jpg
description: Site destinado a divulgação do meu trabalho como Cientista de Dados
show_downloads: true
link_material: "https://www.dropbox.com/s/tpca99zhcnttu72/20200305_WBS-Projeto%20transparencia.pdf?dl=0"
