theme: jekyll-theme-minimal
title: Seja bem vindo ao meu projeto
logo: asset/simbolo_tokyo.png
description: Fique a vontade para olhar o projeto e mandar updates.
show_downloads: true
link_material: "https://www.dropbox.com/s/tpca99zhcnttu72/20200305_WBS-Projeto%20transparencia.pdf?dl=0"
