theme: jekyll-theme-minimal
title: Projeto Tokyo-Data
logo: asset/simbolo_tokyo.png
description: Site com análise sobre de dados do Brasil nas olimpíadas.
show_downloads: true
link_material: "https://www.dropbox.com/s/tpca99zhcnttu72/20200305_WBS-Projeto%20transparencia.pdf?dl=0"
